In [1]:
import duckdb
import ibis
from ibis import _

In [2]:
import os

# Check if the file exists, if not, create it
if not os.path.exists('./db/sonotheque.duckdb'):
    # Create an empty DuckDB file
    duckdb.connect('./db/sonotheque.duckdb').close()
    print("Created sonotheque.duckdb file.")
else:
    print("sonotheque.duckdb file already exists.")

# Create a DuckDB connection
con = duckdb.connect('./db/sonotheque.duckdb')
con.install_extension("spatial")
con.load_extension("spatial")

sonotheque.duckdb file already exists.

In [2]:
con = duckdb.connect('./db/sonotheque.duckdb')

In [3]:
# Show tables in the database
print("Tables in the database:")
print(con.execute("SHOW TABLES").fetchall())

# Show schema for each table
tables = con.execute("SHOW TABLES").fetchall()
for table in tables:
    table_name = table[0]
    print(f"\nSchema for table '{table_name}':")
    schema = con.execute(f"DESCRIBE {table_name}").fetchall()
    for column in schema:
        print(f"  {column[0]}: {column[1]}")

Tables in the database:
[('import_records',), ('records',)]

Schema for table 'import_records':
  SON_PK: BIGINT
  SON_UID: VARCHAR
  TYPE: VARCHAR
  TITRE: VARCHAR
  INSTITUTION_CODE: VARCHAR
  COLLECTION_CODE: VARCHAR
  CATALOG_NUMBER: VARCHAR
  VALIDE: BIGINT
  VALIDE_PAR: VARCHAR
  PUBLIE: BIGINT
  DATE_PUBLICATION_DEBUT: TIMESTAMP
  DATE_PUBLICATION_FIN: TIMESTAMP
  PUBLICATION_SCIENTIFIQUE: VARCHAR
  RECORDER: VARCHAR
  MICRO: VARCHAR
  PARABOLE: BIGINT
  FREQUENCE_ECHANTILLONNAGE: BIGINT
  SUPPORT_ORIGINAL: BIGINT
  QUALITE: BIGINT
  DATE_ENREGISTREMENT_INT: BIGINT
  HEURE_ENREGISTREMENT_INT: BIGINT
  LIEU_ENREGISTREMENT: BIGINT
  TEMPERATURE: VARCHAR
  COMMENTAIRES_ENREGISTREMENT: VARCHAR
  CONTEXTE_COMPORTEMENTAL: VARCHAR
  HABITAT: VARCHAR
  DESCRIPTION_HABITAT: VARCHAR
  CONTINENT_OCEAN: VARCHAR
  PAYS: VARCHAR
  LOCALITE: VARCHAR
  LATITUDE: DOUBLE
  LONGITUDE: DOUBLE
  ALTITUDE: BIGINT
  COMMENTAIRES: VARCHAR
  DATECRE: TIMESTAMP
  DATEMAJ: TIMESTAMP
  USERCRE: VARCHAR
  USERMAJ: VARCHAR
  TELECHARGER_WAV: BIGINT
  DEGRE_CERTITUDE: BIGINT
  LUMINOSITE: BIGINT
  DROITS: VARCHAR
  SON_MODE_IDENTIFICATION_PK: BIGINT
  SON_FK: BIGINT
  MODE_IDENTIFICATION: BIGINT
  VOCABULAIRE_PK: BIGINT
  VOCABULAIRE_CATEGORIE_FK: BIGINT
  LIBELLE_FR: VARCHAR
  LIBELLE_EN: VARCHAR
  OLD_PK: BIGINT
  DATECRE2: TIMESTAMP
  DATEMAJ3: TIMESTAMP
  USERCRE4: VARCHAR
  USERMAJ5: VARCHAR
  SON_ESPECE_PK: BIGINT
  SON_FK6: BIGINT
  ESPECE_FK: BIGINT
  DEGRE_CERTITUDE7: BIGINT
  DATECRE8: TIMESTAMP
  DATEMAJ9: TIMESTAMP
  USERCRE10: VARCHAR
  USERMAJ11: VARCHAR
  ESPECE_PK: BIGINT
  VALIDE12: BIGINT
  GROUPE_TAXONOMIQUE: BIGINT
  ORDRE: VARCHAR
  FAMILLE: VARCHAR
  GENRE: VARCHAR
  EPITHETE_SPECIFIQUE: VARCHAR
  EPITHETE_INFRA_SPECIFIQUE: VARCHAR
  DESCRIPTEUR: VARCHAR
  NOM_SCIENTIFIQUE: VARCHAR
  DATECRE13: TIMESTAMP
  DATEMAJ14: TIMESTAMP
  USERCRE15: VARCHAR
  USERMAJ16: VARCHAR
  NOM_VERNACULAIRE_PK: BIGINT
  ESPECE_FK17: BIGINT
  LANG: VARCHAR
  NOM: VARCHAR
  DATECRE18: TIMESTAMP
  DATEMAJ19: TIMESTAMP
  USERCRE20: VARCHAR
  USERMAJ21: VARCHAR
  VOCABULAIRE_PK22: BIGINT
  VOCABULAIRE_CATEGORIE_FK23: BIGINT
  LIBELLE_FR24: VARCHAR
  LIBELLE_EN25: VARCHAR
  OLD_PK26: BIGINT
  DATECRE27: TIMESTAMP
  DATEMAJ28: TIMESTAMP
  USERCRE29: VARCHAR
  USERMAJ30: VARCHAR
  SON_AUTEUR_PK: BIGINT
  SON_FK31: BIGINT
  AUTEUR_FK: BIGINT
  DATECRE32: TIMESTAMP
  DATEMAJ33: TIMESTAMP
  USERCRE34: VARCHAR
  USERMAJ35: VARCHAR
  AUTEUR_PK: BIGINT
  NOM36: VARCHAR
  DATECRE37: TIMESTAMP
  DATEMAJ38: TIMESTAMP
  USERCRE39: VARCHAR
  USERMAJ40: VARCHAR
  SON_MOT_CLE_PK: BIGINT
  SON_FK41: BIGINT
  MOT_CLE_FK: BIGINT
  DATECRE42: TIMESTAMP
  DATEMAJ43: TIMESTAMP
  USERCRE44: VARCHAR
  USERMAJ45: VARCHAR
  MOT_CLE_PK: BIGINT
  LANG46: VARCHAR
  LIBELLE: VARCHAR
  DATECRE47: TIMESTAMP
  DATEMAJ48: TIMESTAMP
  USERCRE49: VARCHAR
  USERMAJ50: VARCHAR
  SON_SPECIMEN_PK: BIGINT
  SON_FK51: BIGINT
  SPECIMEN_FK: BIGINT
  DATECRE52: TIMESTAMP
  DATEMAJ53: TIMESTAMP
  USERCRE54: VARCHAR
  USERMAJ55: VARCHAR
  SPECIMEN_PK: BIGINT
  INSTITUTION_CODE56: VARCHAR
  COLLECTION_CODE57: VARCHAR
  CATALOG_NUMBER58: VARCHAR
  DATE_COLLECTE_INT: BIGINT
  HEURE_COLLECTE_INT: BIGINT
  LUMINOSITE59: BIGINT
  COLLECTEUR: VARCHAR
  DATECRE60: TIMESTAMP
  DATEMAJ61: TIMESTAMP
  USERCRE62: VARCHAR
  USERMAJ63: VARCHAR
  FICHIER_SON_PK: BIGINT
  SON_FK64: BIGINT
  FICHIER_UID: VARCHAR
  TYPE65: VARCHAR
  PATH: VARCHAR
  FILENAME: VARCHAR
  MIME_TYPE: VARCHAR
  TAILLE: BIGINT
  CHECKSUM: BIGINT
  DUREE: VARCHAR
  BITSPERSAMPLE: BIGINT
  CHANNELS: BIGINT
  FREQUENCE_ECHANTILLONNAGE66: BIGINT
  DATECRE67: TIMESTAMP
  DATEMAJ68: TIMESTAMP
  USERCRE69: VARCHAR
  USERMAJ70: VARCHAR
  SON_IMAGE_PK: BIGINT
  SON_FK71: BIGINT
  IMAGE_FK: BIGINT
  TYPE72: VARCHAR
  DATECRE73: TIMESTAMP
  DATEMAJ74: TIMESTAMP
  USERCRE75: VARCHAR
  USERMAJ76: VARCHAR
  IMAGE_PK: BIGINT
  IMAGE_UID: VARCHAR
  ID: VARCHAR
  MIME_TYPE77: VARCHAR
  MODELE: BIGINT
  TAILLE78: BIGINT
  CHECKSUM79: BIGINT
  LARGEUR: BIGINT
  HAUTEUR: BIGINT
  CREDIT: VARCHAR
  DATECRE80: TIMESTAMP
  DATEMAJ81: TIMESTAMP
  USERCRE82: VARCHAR
  USERMAJ83: VARCHAR

Schema for table 'records':
  SON_PK: BIGINT
  SON_UID: VARCHAR
  TYPE: VARCHAR
  TITRE: VARCHAR
  INSTITUTION_CODE: VARCHAR
  COLLECTION_CODE: VARCHAR
  CATALOG_NUMBER: VARCHAR
  VALIDE: BIGINT
  VALIDE_PAR: VARCHAR
  PUBLIE: BIGINT
  DATE_PUBLICATION_DEBUT: TIMESTAMP
  DATE_PUBLICATION_FIN: TIMESTAMP
  PUBLICATION_SCIENTIFIQUE: VARCHAR
  RECORDER: VARCHAR
  MICRO: VARCHAR
  PARABOLE: BIGINT
  FREQUENCE_ECHANTILLONNAGE: BIGINT
  SUPPORT_ORIGINAL: BIGINT
  QUALITE: BIGINT
  DATE_ENREGISTREMENT_INT: BIGINT
  HEURE_ENREGISTREMENT_INT: BIGINT
  LIEU_ENREGISTREMENT: BIGINT
  TEMPERATURE: VARCHAR
  COMMENTAIRES_ENREGISTREMENT: VARCHAR
  CONTEXTE_COMPORTEMENTAL: VARCHAR
  HABITAT: VARCHAR
  DESCRIPTION_HABITAT: VARCHAR
  CONTINENT_OCEAN: VARCHAR
  PAYS: VARCHAR
  LOCALITE: VARCHAR
  LATITUDE: DOUBLE
  LONGITUDE: DOUBLE
  ALTITUDE: BIGINT
  COMMENTAIRES: VARCHAR
  DATECRE: TIMESTAMP
  DATEMAJ: TIMESTAMP
  USERCRE: VARCHAR
  USERMAJ: VARCHAR
  TELECHARGER_WAV: BIGINT
  DEGRE_CERTITUDE: BIGINT
  LUMINOSITE: BIGINT
  DROITS: VARCHAR
  SON_MODE_IDENTIFICATION_PK: BIGINT
  SON_FK: BIGINT
  MODE_IDENTIFICATION: BIGINT
  VOCABULAIRE_PK: BIGINT
  VOCABULAIRE_CATEGORIE_FK: BIGINT
  LIBELLE_FR: VARCHAR
  LIBELLE_EN: VARCHAR
  OLD_PK: BIGINT
  DATECRE2: TIMESTAMP
  DATEMAJ3: TIMESTAMP
  USERCRE4: VARCHAR
  USERMAJ5: VARCHAR
  SON_ESPECE_PK: BIGINT
  SON_FK6: BIGINT
  ESPECE_FK: BIGINT
  DEGRE_CERTITUDE7: BIGINT
  DATECRE8: TIMESTAMP
  DATEMAJ9: TIMESTAMP
  USERCRE10: VARCHAR
  USERMAJ11: VARCHAR
  ESPECE_PK: BIGINT
  VALIDE12: BIGINT
  GROUPE_TAXONOMIQUE: BIGINT
  ORDRE: VARCHAR
  FAMILLE: VARCHAR
  GENRE: VARCHAR
  EPITHETE_SPECIFIQUE: VARCHAR
  EPITHETE_INFRA_SPECIFIQUE: VARCHAR
  DESCRIPTEUR: VARCHAR
  NOM_SCIENTIFIQUE: VARCHAR
  DATECRE13: TIMESTAMP
  DATEMAJ14: TIMESTAMP
  USERCRE15: VARCHAR
  USERMAJ16: VARCHAR
  NOM_VERNACULAIRE_PK: BIGINT
  ESPECE_FK17: BIGINT
  LANG: VARCHAR
  NOM: VARCHAR
  DATECRE18: TIMESTAMP
  DATEMAJ19: TIMESTAMP
  USERCRE20: VARCHAR
  USERMAJ21: VARCHAR
  VOCABULAIRE_PK22: BIGINT
  VOCABULAIRE_CATEGORIE_FK23: BIGINT
  LIBELLE_FR24: VARCHAR
  LIBELLE_EN25: VARCHAR
  OLD_PK26: BIGINT
  DATECRE27: TIMESTAMP
  DATEMAJ28: TIMESTAMP
  USERCRE29: VARCHAR
  USERMAJ30: VARCHAR
  SON_AUTEUR_PK: BIGINT
  SON_FK31: BIGINT
  AUTEUR_FK: BIGINT
  DATECRE32: TIMESTAMP
  DATEMAJ33: TIMESTAMP
  USERCRE34: VARCHAR
  USERMAJ35: VARCHAR
  AUTEUR_PK: BIGINT
  NOM36: VARCHAR
  DATECRE37: TIMESTAMP
  DATEMAJ38: TIMESTAMP
  USERCRE39: VARCHAR
  USERMAJ40: VARCHAR
  SON_MOT_CLE_PK: BIGINT
  SON_FK41: BIGINT
  MOT_CLE_FK: BIGINT
  DATECRE42: TIMESTAMP
  DATEMAJ43: TIMESTAMP
  USERCRE44: VARCHAR
  USERMAJ45: VARCHAR
  MOT_CLE_PK: BIGINT
  LANG46: VARCHAR
  LIBELLE: VARCHAR
  DATECRE47: TIMESTAMP
  DATEMAJ48: TIMESTAMP
  USERCRE49: VARCHAR
  USERMAJ50: VARCHAR
  SON_SPECIMEN_PK: BIGINT
  SON_FK51: BIGINT
  SPECIMEN_FK: BIGINT
  DATECRE52: TIMESTAMP
  DATEMAJ53: TIMESTAMP
  USERCRE54: VARCHAR
  USERMAJ55: VARCHAR
  SPECIMEN_PK: BIGINT
  INSTITUTION_CODE56: VARCHAR
  COLLECTION_CODE57: VARCHAR
  CATALOG_NUMBER58: VARCHAR
  DATE_COLLECTE_INT: BIGINT
  HEURE_COLLECTE_INT: BIGINT
  LUMINOSITE59: BIGINT
  COLLECTEUR: VARCHAR
  DATECRE60: TIMESTAMP
  DATEMAJ61: TIMESTAMP
  USERCRE62: VARCHAR
  USERMAJ63: VARCHAR
  FICHIER_SON_PK: BIGINT
  SON_FK64: BIGINT
  FICHIER_UID: VARCHAR
  TYPE65: VARCHAR
  PATH: VARCHAR
  FILENAME: VARCHAR
  MIME_TYPE: VARCHAR
  TAILLE: BIGINT
  CHECKSUM: BIGINT
  DUREE: VARCHAR
  BITSPERSAMPLE: BIGINT
  CHANNELS: BIGINT
  FREQUENCE_ECHANTILLONNAGE66: BIGINT
  DATECRE67: TIMESTAMP
  DATEMAJ68: TIMESTAMP
  USERCRE69: VARCHAR
  USERMAJ70: VARCHAR
  SON_IMAGE_PK: BIGINT
  SON_FK71: BIGINT
  IMAGE_FK: BIGINT
  TYPE72: VARCHAR
  DATECRE73: TIMESTAMP
  DATEMAJ74: TIMESTAMP
  USERCRE75: VARCHAR
  USERMAJ76: VARCHAR
  IMAGE_PK: BIGINT
  IMAGE_UID: VARCHAR
  ID: VARCHAR
  MIME_TYPE77: VARCHAR
  MODELE: BIGINT
  TAILLE78: BIGINT
  CHECKSUM79: BIGINT
  LARGEUR: BIGINT
  HAUTEUR: BIGINT
  CREDIT: VARCHAR
  DATECRE80: TIMESTAMP
  DATEMAJ81: TIMESTAMP
  USERCRE82: VARCHAR
  USERMAJ83: VARCHAR

In [4]:
# Count all rows in the 'records' table
row_count = con.execute("SELECT COUNT(*) FROM records").fetchone()[0]
print(f"Total number of rows in the 'records' table: {row_count}")

Total number of rows in the 'records' table: 1048575

In [ ]:
# Aggregate records based on SON_PK and return first NOM_SCIENTIFIQUE
result = con.execute("""
    SELECT 
        SON_PK,
        FIRST(SON_UID) AS SON_UID,
        FIRST(COLLECTION_CODE) AS COLLECTION_CODE,
        FIRST(NOM_SCIENTIFIQUE) AS NOM_SCIENTIFIQUE
    FROM records
    GROUP BY SON_PK
""").fetchall()

# Display the first few results
print("Aggregated records (first 50):")
for row in result[:50]:
    print(f"SON_PK: {row[0]}, SON_UID: {row[1]}, COLLECTION_CODE: {row[2]}, NOM_SCIENTIFIQUE: {row[3]}")

# Get the total count of unique SON_PK
unique_count = con.execute("SELECT COUNT(DISTINCT SON_PK) FROM records").fetchone()[0]
print(f"\nTotal number of unique SON_PK: {unique_count}")

In [ ]:
# Aggregate records based on SON_PK and return first NOM_SCIENTIFIQUE
result = con.execute("""
    SELECT 
        NOM_SCIENTIFIQUE,
        FIRST(SON_UID) AS SON_UID,
        FIRST(COLLECTION_CODE) AS COLLECTION_CODE,
    FROM records
    GROUP BY NOM_SCIENTIFIQUE
""").fetchall()

# Display the first few results
print("Aggregated records (first 50):")
for row in result[:50]:
    print(f"NOM_SCIENTIFIQUE: {row[0]}, SON_UID: {row[1]}, COLLECTION_CODE: {row[2]}")




# Get the total count of unique SON_PK
unique_count = con.execute("SELECT COUNT(DISTINCT NOM_SCIENTIFIQUE) FROM records").fetchone()[0]
print(f"\nTotal number of unique SON_PK: {unique_count}")

In [14]:
con.sql("""
    SELECT 
        NOM_SCIENTIFIQUE,
        FIRST(SON_UID) AS SON_UID,
        FIRST(COLLECTION_CODE) AS COLLECTION_CODE,
    FROM records
    GROUP BY NOM_SCIENTIFIQUE
""").show()

┌──────────────────────────────────────────────────┬───────────────────────────────┬─────────────────┐
│                 NOM_SCIENTIFIQUE                 │            SON_UID            │ COLLECTION_CODE │
│                     varchar                      │            varchar            │     varchar     │
├──────────────────────────────────────────────────┼───────────────────────────────┼─────────────────┤
│ Hyla arborea (Linnaeus, 1758)                    │ 1423750549968saMd3IX4atyu8Osf │ SO              │
│ Gryllus campestris Linnaeus, 1758                │ 13867749528019ZTeQN2bXAkp7vVn │ SO              │
│ Notosciobia sp affinis paranola Otte, 1987       │ 1452140705499viYCyHQU70KGgIAU │ SO              │
│ Phonarellus minor (Chopard,1959)                 │ 1389780653418oIPwvLh4XYRHyr2V │ SO              │
│ Cardiodactylus kondoi Otte, 2007                 │ 1431533770611Ygcat0MITMCbsJRe │ SO              │
│ Acanthogryllus asiaticus Gorochov, 1990          │ 1467386703444ufUnTqILQLySRPZX │ SO              │
│ Acrocephalus baeticus (Vieillot, 1817)           │ 1467988989503VajBhksOKYapYdNT │ SO              │
│ Pirates stridulus (Fabricius, 1737)              │ 142736394288366Zuf96FjZgQZ08h │ SO              │
│ Pixibinthus sonicus Anso & User3d, 2016          │ 14407547239319F1Mkhtta6S2oL72 │ SO              │
│ Typhlobrixia namorokensis Synave, 1953           │ 1441099944958o8ohzxRgNQJtV83C │ SO              │
│                ·                                 │               ·               │ ·               │
│                ·                                 │               ·               │ ·               │
│                ·                                 │               ·               │ ·               │
│ Todirostrum pictum Salvin, 1897                  │ 1468364544839H7AyKQrHMirJR9qw │ SO              │
│ Turdus fuscater d'Orbigny & Lafresnaye, 1837     │ 1468366534880wy2cL06yzjgl8fqB │ SO              │
│ Tetraogallus caucasicus (Pallas, 1811)           │ 1468361352317iw6SbTG1mVLpVo60 │ SO              │
│ Sylvietta rufescens (Vieillot, 1817)             │ 14683603490189uiGQxZsx5VjdPl6 │ SO              │
│ Thalasseus sandvicensis (Latham, 1787)           │ 1468363490118JV9bP4veRlSP8RPx │ SO              │
│ Tadorna tadorna (Linnaeus, 1758)                 │ 14683607258867gp9HvF3P2MlH63b │ SO              │
│ Tamias sibiricus (Laxmann, 1769)                 │ 1468360804569moZHnZiF91ccBCXi │ SO              │
│ Trogon collaris Vieillot, 1817                   │ 1468366131767kXu8zMlWk7jFq9iM │ SO              │
│ Trogon violaceus Gmelin, JF, 1788                │ 1468366151893nqKM94gDyW9uFMs0 │ SO              │
│ Euchrepomis spodioptila (Sclater & Salvin, 1881) │ 14683611742115AYasM7WBN3exg4T │ SO              │
├──────────────────────────────────────────────────┴───────────────────────────────┴─────────────────┤
│ 1703 rows (20 shown)                                                                     3 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
# con.sql("""
#     INSTALL spatial;
# LOAD spatial;
#     ALTER TABLE records
#     ADD COLUMN geometry GEOMETRY;

#     UPDATE records
#     SET geometry = ST_Point(LONGITUDE::FLOAT, LATITUDE::FLOAT)
#     WHERE LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL;
# """)


# Verify the new geometry column
con.sql("""
    SELECT 
        NOM_SCIENTIFIQUE,
        LATITUDE,
        LONGITUDE,
        ST_AsText(geometry) AS geometry_wkt
    FROM records
    WHERE geometry IS NOT NULL
    LIMIT 5
""").show()

print("\nTotal records with valid geometry:")

In [19]:
con.sql("SELECT COUNT(*) FROM records WHERE geometry IS NOT NULL").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       202663 │
└──────────────┘

In [ ]:
# Aggregate records based on SON_PK and return first NOM_SCIENTIFIQUE
result = con.sql("""
    SELECT 
        uuid() AS UUID,
        NOM_SCIENTIFIQUE,
        LIST(SON_UID) AS SON_UIDS,
        FIRST(COLLECTION_CODE) AS COLLECTION_CODE,
    FROM records
    GROUP BY NOM_SCIENTIFIQUE
""")

In [ ]:
# results_df = con.sql("""
#     SELECT 
#         uuid() AS UUID,
#         NOM_SCIENTIFIQUE,
#         LIST(SON_UID) AS SON_UIDS,
#         FIRST(COLLECTION_CODE) AS COLLECTION_CODE,
#     FROM records
#     GROUP BY NOM_SCIENTIFIQUE
# """).df()

# results_df.head()

In [3]:
# Add a UUID column to records and generate a UUID for each unique SON_UID value
con.sql("""
    ALTER TABLE records
    ADD COLUMN record_uuid UUID;
""")

# Generate and assign UUIDs for each unique SON_UID
con.sql("""
    WITH unique_son_uids AS (
        SELECT DISTINCT SON_UID
        FROM records
    ),
    uuid_mapping AS (
        SELECT 
            SON_UID,
            uuid() AS new_uuid
        FROM unique_son_uids
    )
    UPDATE records
    SET record_uuid = uuid_mapping.new_uuid
    FROM uuid_mapping
    WHERE records.SON_UID = uuid_mapping.SON_UID;
""")

# Verify the new column and data
print("Sample of records with new UUID column:")
con.sql("""
    SELECT 
        record_uuid,
        SON_UID,
        NOM_SCIENTIFIQUE,
        COUNT(*) OVER (PARTITION BY SON_UID) as records_per_son_uid
    FROM records
    ORDER BY SON_UID
    LIMIT 10
""").show()

Sample of records with new UUID column:
┌──────────────────────┬───────────────────────────────┬─────────────────────────────────────────┬─────────────────────┐
│     record_uuid      │            SON_UID            │            NOM_SCIENTIFIQUE             │ records_per_son_uid │
│         uuid         │            varchar            │                 varchar                 │        int64        │
├──────────────────────┼───────────────────────────────┼─────────────────────────────────────────┼─────────────────────┤
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ c68e096d-49d0-416e…  │ 1379684303448THUEerYPSdH2oaAy │ Cicada barbara lusitanica Boulard, 1982 │                   6 │
│ de52a5a1-0490-4db6…  │ 1380199964961x6LFFSa28I2OPqaw │ Cicadetta brevipennis Fieber, 1876      │                   6 │
│ de52a5a1-0490-4db6…  │ 1380199964961x6LFFSa28I2OPqaw │ Cicadetta brevipennis Fieber, 1876      │                   6 │
│ de52a5a1-0490-4db6…  │ 1380199964961x6LFFSa28I2OPqaw │ Cicadetta brevipennis Fieber, 1876      │                   6 │
│ de52a5a1-0490-4db6…  │ 1380199964961x6LFFSa28I2OPqaw │ Cicadetta brevipennis Fieber, 1876      │                   6 │
├──────────────────────┴───────────────────────────────┴─────────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                                                    4 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


Total number of unique SON_UIDs:
┌─────────────────────────┐
│ count(DISTINCT SON_UID) │
│          int64          │
├─────────────────────────┤
│                   30966 │
└─────────────────────────┘


Total number of records with UUID:
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       227491 │
└──────────────┘

In [4]:

print("\nTotal number of unique SON_UIDs:")
con.sql("SELECT COUNT(DISTINCT SON_UID) FROM records").show()

print("\nTotal number of records with UUID:")
con.sql("SELECT COUNT(DISTINCT record_uuid) FROM records").show()

Total number of unique SON_UIDs:
┌─────────────────────────┐
│ count(DISTINCT SON_UID) │
│          int64          │
├─────────────────────────┤
│                   30966 │
└─────────────────────────┘


Total number of records with UUID:
┌─────────────────────────────┐
│ count(DISTINCT record_uuid) │
│            int64            │
├─────────────────────────────┤
│                       30966 │
└─────────────────────────────┘